[package]
name = "QRFS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = "0.7"
fuse = "0.3.1"
serde = "1.0.136"
libc = "0.2.16"
time = "0.1"